// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gsxhnd/tenhou/api/handler"
	"github.com/gsxhnd/tenhou/api/middleware"
	"github.com/gsxhnd/tenhou/api/router"
	"github.com/gsxhnd/tenhou/api/service"
)

// Injectors from wire.go:

func InitApp() (*Application, error) {
	middlewarer := middleware.NewMiddleware()
	pingService := service.NewPingService()
	pingHandler := handler.NewPingHandler(pingService)
	handlerHandler := handler.Handler{
		PingHandler: pingHandler,
	}
	routerRouter, err := router.NewRouter(middlewarer, handlerHandler)
	if err != nil {
		return nil, err
	}
	application := NewApplication(routerRouter)
	return application, nil
}
