// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gsxhnd/tenhou/api/handler"
	"github.com/gsxhnd/tenhou/api/middleware"
	"github.com/gsxhnd/tenhou/api/router"
	"github.com/gsxhnd/tenhou/api/service"
	"github.com/gsxhnd/tenhou/db"
	"github.com/gsxhnd/tenhou/utils"
)

// Injectors from wire.go:

func InitApp() (*Application, error) {
	config, err := utils.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := utils.NewLogger(config)
	middlewarer := middleware.NewMiddleware(logger)
	database, err := db.NewDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	pingService := service.NewPingService(logger, database)
	pingHandler := handler.NewPingHandler(pingService)
	validate := utils.NewValidator()
	logService := service.NewLogService(logger, database)
	logHandler := handler.NewLogHandler(validate, logger, logService)
	handlerHandler := handler.Handler{
		PingHandler: pingHandler,
		LogHandler:  logHandler,
	}
	routerRouter, err := router.NewRouter(config, middlewarer, handlerHandler)
	if err != nil {
		return nil, err
	}
	application := NewApplication(routerRouter)
	return application, nil
}
