name: Cron Update Data

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22
        id: go

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Download Database
        uses: robinraju/release-downloader@v1
        with:
          tag: "db"
          fileName: "tenhou*"
          out-file-path: "./data"
          extract: true

      - name: test
        run: ls -al ./
      - run: ls -al ./data
