name: Cron Update Data

on:
  schedule:
    - cron: "0 0 * * 1"

env:
  FILE_DATE: $(date +'%Y%m%d')

jobs:
  Test:
    name: Cron
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22
        id: go
      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Download default database
        uses: robinraju/release-downloader@v1
        with:
          tag: "db"
          fileName: "tenhou_data.zip"
          out-file-path: "./data"
          extract: true
      - name: unzip default database
        run: unzip ./data/tenhou_data.zip
      - run: mkdir ./data/tenhou_html && ls -al ./data

      - name: download recent data
        run: go run ./cmd download_recent
      - run: ls -al ./data/tenhou_html
      - name: store to db
        run: go run ./cmd recent_html_to_db

      - name: zip default database
        run: zip ./data/tenhou_data.zip ./data/tenhou_data.db
      - name: rename db to archive db
        run: mv ./data/tenhou_data.db ./data/tenhou_data.${{ steps.date.outputs.date }}.db
      - name: zip archive db
        run: zip ./data/tenhou_data.${{ steps.date.outputs.date }}.zip ./data/tenhou_data.${{ steps.date.outputs.date }}.db

      - name: Upload archive database
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./data/tenhou_data.${{ steps.date.outputs.date }}.zip
          tag: db

      - name: Upload default database
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./data/tenhou_data.zip
          tag: db
          overwrite: true
