name: Cron Update Data

on:
  schedule:
    - cron: "0 0 * * 1"
  push:

env:
  FILE_DATE: $(date +'%Y%m%d')

jobs:
  Test:
    name: Cron
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - run: echo ${{ steps.date.outputs.date }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22
        id: go

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Download Database
        uses: robinraju/release-downloader@v1
        with:
          tag: "db"
          fileName: "tenhou*"
          out-file-path: "./data"
          extract: true

      - name: unzip data
        run: unzip ./data/tenhou_data.zip
      - run: mkdir ./data/tenhou_html && ls -al ./data

      - name: download recent data
        run: go run ./cmd download_recent
      - run: ls -al ./data/tenhou_html
      - name: store to db
        run: go run ./cmd recent_html_to_db

      - name: zip
        run: zip ./data/tenhou_data.zip ./data/tenhou_data.db

      - name: rename db
        run: mv ./data/tenhou_data.db ./data/tenhou_data.$(date +'%Y%m%d').db

      - name: zip
        run: zip ./data/tenhou_data.$(date +'%Y%m%d').zip ./data/tenhou_data.$(date +'%Y%m%d').db

      - run: ls -al ./data

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./data/tenhou_data.$(date +'%Y%m%d').zip
          tag: db

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./data/tenhou_data.zip
          tag: db
          overwrite: true
